# Generated by Django 4.1.5 on 2023-02-23 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('avatar', models.ImageField(null=True, upload_to='avatars/')),
                ('position', models.CharField(max_length=50)),
                ('bio', models.TextField()),
            ],
            options={
                'ordering': ['firstname'],
            },
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(null=True, upload_to='news_media/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.ForeignKey(default='Null', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='news_author', to='news.author'),
        ),
    ]
